//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroSessionOrganizerResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AstroSessionOrganizerModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actualisation de la liste des équipements.
        /// </summary>
        public static string ActualisationDeLaListeDesEquipements {
            get {
                return ResourceManager.GetString("ActualisationDeLaListeDesEquipements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actualisation de la liste des objets célestes.
        /// </summary>
        public static string ActualisationDeLaListeDesObjetsCelestes {
            get {
                return ResourceManager.GetString("ActualisationDeLaListeDesObjetsCelestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actualisation de la liste des sessions.
        /// </summary>
        public static string ActualisationDeLaListeDesSessions {
            get {
                return ResourceManager.GetString("ActualisationDeLaListeDesSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher la session d&apos;observations sélectionnée.
        /// </summary>
        public static string AfficherLaSessionDObservationsSelectionnee {
            get {
                return ResourceManager.GetString("AfficherLaSessionDObservationsSelectionnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher l&apos;objet céleste.
        /// </summary>
        public static string AfficherLObjetCeleste {
            get {
                return ResourceManager.GetString("AfficherLObjetCeleste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher l&apos;objet céleste dans AstroTargetSelector (bientôt disponible).
        /// </summary>
        public static string AfficherLObjetCelesteDansAstroTargetSelector {
            get {
                return ResourceManager.GetString("AfficherLObjetCelesteDansAstroTargetSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher l&apos;objet céleste dans Cartes du Ciel.
        /// </summary>
        public static string AfficherLObjetCelesteDansCartesDuCiel {
            get {
                return ResourceManager.GetString("AfficherLObjetCelesteDansCartesDuCiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher l&apos;objet céleste dans Stellarium.
        /// </summary>
        public static string AfficherLObjetCelesteDansStellarium {
            get {
                return ResourceManager.GetString("AfficherLObjetCelesteDansStellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajout d&apos;une obsevation.
        /// </summary>
        public static string AjoutDUneObsevation {
            get {
                return ResourceManager.GetString("AjoutDUneObsevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter le logiciel sélectionné à la session.
        /// </summary>
        public static string AjouterLeLogicielSelectionneALaSession {
            get {
                return ResourceManager.GetString("AjouterLeLogicielSelectionneALaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter l&apos;équipement au setup.
        /// </summary>
        public static string AjouterLEquipementAuSetup {
            get {
                return ResourceManager.GetString("AjouterLEquipementAuSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter l&apos;équipement sélectionné à la session.
        /// </summary>
        public static string AjouterLEquipementSelectionneALaSession {
            get {
                return ResourceManager.GetString("AjouterLEquipementSelectionneALaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter/supprimer des logiciels à la session.
        /// </summary>
        public static string AjouterSupprimerDesLogicielsALaSession {
            get {
                return ResourceManager.GetString("AjouterSupprimerDesLogicielsALaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une image au setup.
        /// </summary>
        public static string AjouterUneImageAuSetup {
            get {
                return ResourceManager.GetString("AjouterUneImageAuSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une image au site d&apos;observations.
        /// </summary>
        public static string AjouterUneImageAuSiteDObservations {
            get {
                return ResourceManager.GetString("AjouterUneImageAuSiteDObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une observation à la session.
        /// </summary>
        public static string AjouterUneObservationALaSession {
            get {
                return ResourceManager.GetString("AjouterUneObservationALaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Août.
        /// </summary>
        public static string Aout {
            get {
                return ResourceManager.GetString("Aout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A propos de.
        /// </summary>
        public static string AProposDe {
            get {
                return ResourceManager.GetString("AProposDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention, les modifications apportées à vos setup vont concerner toutes les sessions d&apos;observations utilisant ce setup..
        /// </summary>
        public static string AttentionLesModificationsApporteesAVosSetupVontConcernerToutesLesSessionsDObservationsUtilisantCeSetup {
            get {
                return ResourceManager.GetString("AttentionLesModificationsApporteesAVosSetupVontConcernerToutesLesSessionsDObserva" +
                        "tionsUtilisantCeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention, les modifications du nom de l&apos;équipement ne seront plus prises en compte..
        /// </summary>
        public static string AttentionLesModificationsDuNomDeLEquipementNeSerontPlusPrisesEnCompte {
            get {
                return ResourceManager.GetString("AttentionLesModificationsDuNomDeLEquipementNeSerontPlusPrisesEnCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun.
        /// </summary>
        public static string Aucun {
            get {
                return ResourceManager.GetString("Aucun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune session associée.
        /// </summary>
        public static string AucuneSessionAssociee {
            get {
                return ResourceManager.GetString("AucuneSessionAssociee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avril.
        /// </summary>
        public static string Avril {
            get {
                return ResourceManager.GetString("Avril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Base de données.
        /// </summary>
        public static string BaseDeDonnees {
            get {
                return ResourceManager.GetString("BaseDeDonnees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BETA.
        /// </summary>
        public static string BETA {
            get {
                return ResourceManager.GetString("BETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Binning.
        /// </summary>
        public static string Binning {
            get {
                return ResourceManager.GetString("Binning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bortle.
        /// </summary>
        public static string Bortle {
            get {
                return ResourceManager.GetString("Bortle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à brutes.
        /// </summary>
        public static string brutes {
            get {
                return ResourceManager.GetString("brutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catalogues.
        /// </summary>
        public static string Catalogues {
            get {
                return ResourceManager.GetString("Catalogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce logiciel n&apos;apparaîtra plus dans les sessions dans lesquelles il est présent..
        /// </summary>
        public static string CeLogicielNApparaitraPlusDansLesSessionsDansLesquellesIlEstPresent {
            get {
                return ResourceManager.GetString("CeLogicielNApparaitraPlusDansLesSessionsDansLesquellesIlEstPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ces données font partie d’un projet scientifique soumis au Copyright..
        /// </summary>
        public static string CesDonneesFontPartieDUnProjetScientifiqueSoumisAuCopyright {
            get {
                return ResourceManager.GetString("CesDonneesFontPartieDUnProjetScientifiqueSoumisAuCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce setup n&apos;apparaîtra plus dans les sessions dans lesquelles il est présent..
        /// </summary>
        public static string CeSetupNApparaitraPlusDansLesSessionsDansLesquellesIlEstPresent {
            get {
                return ResourceManager.GetString("CeSetupNApparaitraPlusDansLesSessionsDansLesquellesIlEstPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce site n&apos;apparaîtra plus dans les sessions dans lesquelles il est présent..
        /// </summary>
        public static string CeSiteNApparaitraPlusDansLesSessionsDansLesquellesIlEstPresent {
            get {
                return ResourceManager.GetString("CeSiteNApparaitraPlusDansLesSessionsDansLesquellesIlEstPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet équipement n&apos;apparaîtra plus dans les sessions et observations dans lesquelles il est présent..
        /// </summary>
        public static string CetEquipementNApparaitraPlusDansLesSessionsEtObservationsDansLesquellesIlEstPresent {
            get {
                return ResourceManager.GetString("CetEquipementNApparaitraPlusDansLesSessionsEtObservationsDansLesquellesIlEstPrese" +
                        "nt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Champ obligatoire.
        /// </summary>
        public static string ChampObligatoire {
            get {
                return ResourceManager.GetString("ChampObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Champs obligatoires manquants.
        /// </summary>
        public static string ChampsObligatoiresManquants {
            get {
                return ResourceManager.GetString("ChampsObligatoiresManquants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement d&apos;une nouvelle image pour la session.
        /// </summary>
        public static string ChargementDUneNouvelleImagePourLaSession {
            get {
                return ResourceManager.GetString("ChargementDUneNouvelleImagePourLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement d&apos;une nouvelle image pour le setup.
        /// </summary>
        public static string ChargementDUneNouvelleImagePourLeSetup {
            get {
                return ResourceManager.GetString("ChargementDUneNouvelleImagePourLeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement d&apos;une nouvelle image pour le site d&apos;observations.
        /// </summary>
        public static string ChargementDUneNouvelleImagePourLeSiteDObservations {
            get {
                return ResourceManager.GetString("ChargementDUneNouvelleImagePourLeSiteDObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commentaires.
        /// </summary>
        public static string Commentaires {
            get {
                return ResourceManager.GetString("Commentaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Constellation.
        /// </summary>
        public static string Constellation {
            get {
                return ResourceManager.GetString("Constellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Constellations.
        /// </summary>
        public static string Constellations {
            get {
                return ResourceManager.GetString("Constellations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contributeurs.
        /// </summary>
        public static string Contributeurs {
            get {
                return ResourceManager.GetString("Contributeurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;un équipement.
        /// </summary>
        public static string CreationDUnEquipement {
            get {
                return ResourceManager.GetString("CreationDUnEquipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;une session d&apos;observations.
        /// </summary>
        public static string CreationDUneSessionDObservations {
            get {
                return ResourceManager.GetString("CreationDUneSessionDObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;un logiciel.
        /// </summary>
        public static string CreationDUnLogiciel {
            get {
                return ResourceManager.GetString("CreationDUnLogiciel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;un objet céleste.
        /// </summary>
        public static string CreationDUnObjetCeleste {
            get {
                return ResourceManager.GetString("CreationDUnObjetCeleste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;un setup.
        /// </summary>
        public static string CreationDUnSetup {
            get {
                return ResourceManager.GetString("CreationDUnSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création d&apos;un site.
        /// </summary>
        public static string CreationDUnSite {
            get {
                return ResourceManager.GetString("CreationDUnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un nouveau logiciel.
        /// </summary>
        public static string CreerUnNouveauLogiciel {
            get {
                return ResourceManager.GetString("CreerUnNouveauLogiciel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un nouveau site d&apos;observations.
        /// </summary>
        public static string CreerUnNouveauSiteDObservations {
            get {
                return ResourceManager.GetString("CreerUnNouveauSiteDObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un nouvel équipement.
        /// </summary>
        public static string CreerUnNouvelEquipement {
            get {
                return ResourceManager.GetString("CreerUnNouvelEquipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DEC.
        /// </summary>
        public static string DEC {
            get {
                return ResourceManager.GetString("DEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Décembre.
        /// </summary>
        public static string Decembre {
            get {
                return ResourceManager.GetString("Decembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déjà observés.
        /// </summary>
        public static string DejaObserves {
            get {
                return ResourceManager.GetString("DejaObserves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Démarrer l&apos;application AstroTargetSelector.
        /// </summary>
        public static string DemarrerLApplicationAstroTargetSelector {
            get {
                return ResourceManager.GetString("DemarrerLApplicationAstroTargetSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dénominations.
        /// </summary>
        public static string Denominations {
            get {
                return ResourceManager.GetString("Denominations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dimension exprimée en secondes d&apos;arc (&apos;).
        /// </summary>
        public static string DimensionExprimeeEnSecondesDArc {
            get {
                return ResourceManager.GetString("DimensionExprimeeEnSecondesDArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Distance (Mpc).
        /// </summary>
        public static string DistanceMpc {
            get {
                return ResourceManager.GetString("DistanceMpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edition de la session du.
        /// </summary>
        public static string EditionDeLaSessionDu {
            get {
                return ResourceManager.GetString("EditionDeLaSessionDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edition de l&apos;objet céleste.
        /// </summary>
        public static string EditionDeLObjetCeleste {
            get {
                return ResourceManager.GetString("EditionDeLObjetCeleste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edition d&apos;une obsevation.
        /// </summary>
        public static string EditionDUneObsevation {
            get {
                return ResourceManager.GetString("EditionDUneObsevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edition d&apos;un équipement.
        /// </summary>
        public static string EditionDUnEquipement {
            get {
                return ResourceManager.GetString("EditionDUnEquipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edition d&apos;une session d&apos;observations.
        /// </summary>
        public static string EditionDUneSessionDObservations {
            get {
                return ResourceManager.GetString("EditionDUneSessionDObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edition d&apos;un logiciel.
        /// </summary>
        public static string EditionDUnLogiciel {
            get {
                return ResourceManager.GetString("EditionDUnLogiciel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edition d&apos;un objet céleste.
        /// </summary>
        public static string EditionDUnObjetCeleste {
            get {
                return ResourceManager.GetString("EditionDUnObjetCeleste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edition d&apos;un setup.
        /// </summary>
        public static string EditionDUnSetup {
            get {
                return ResourceManager.GetString("EditionDUnSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edition d&apos;un site.
        /// </summary>
        public static string EditionDUnSite {
            get {
                return ResourceManager.GetString("EditionDUnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à effectuée avec succès.
        /// </summary>
        public static string EffectueeAvecSucces {
            get {
                return ResourceManager.GetString("EffectueeAvecSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enlever l&apos;équipement du setup.
        /// </summary>
        public static string EnleverLEquipementDuSetup {
            get {
                return ResourceManager.GetString("EnleverLEquipementDuSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoi de la commande.
        /// </summary>
        public static string EnvoiDeLaCommande {
            get {
                return ResourceManager.GetString("EnvoiDeLaCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Equipement.
        /// </summary>
        public static string Equipement {
            get {
                return ResourceManager.GetString("Equipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Equipements.
        /// </summary>
        public static string Equipements {
            get {
                return ResourceManager.GetString("Equipements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Février.
        /// </summary>
        public static string Fevrier {
            get {
                return ResourceManager.GetString("Fevrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtre.
        /// </summary>
        public static string Filtre {
            get {
                return ResourceManager.GetString("Filtre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format attendu : xx° xx&apos; xx,xx&quot;.
        /// </summary>
        public static string FormatAttenduxxDxxxxxx {
            get {
                return ResourceManager.GetString("FormatAttenduxxDxxxxxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format attendu : xxh xx&apos; xx,xx&quot;.
        /// </summary>
        public static string FormatAttenduxxhxxxxx {
            get {
                return ResourceManager.GetString("FormatAttenduxxhxxxxx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format des champs pour le plugin Stellarium incorrect.
        /// </summary>
        public static string FormatDesChampsPourLePluginStellariumIncorrect {
            get {
                return ResourceManager.GetString("FormatDesChampsPourLePluginStellariumIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Binning incorrect.
        /// </summary>
        public static string FormatDuChampBinningIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampBinningIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ DEC incorrect.
        /// </summary>
        public static string FormatDuChampDECIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampDECIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Distance incorrect.
        /// </summary>
        public static string FormatDuChampDistanceIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampDistanceIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Gain incorrect.
        /// </summary>
        public static string FormatDuChampGainIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampGainIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Grandeur Max incorrect.
        /// </summary>
        public static string FormatDuChampGrandeurMaxIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampGrandeurMaxIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Grandeur Min incorrect.
        /// </summary>
        public static string FormatDuChampGrandeurMinIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampGrandeurMinIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Indice Bortle incorrect.
        /// </summary>
        public static string FormatDuChampIndiceBortleIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampIndiceBortleIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Magnitude Photo incorrect.
        /// </summary>
        public static string FormatDuChampMagnitudePhotoIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampMagnitudePhotoIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Magnitude Visuel incorrect.
        /// </summary>
        public static string FormatDuChampMagnitudeVisuelIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampMagnitudeVisuelIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Nombre d&apos;expositions incorrect.
        /// </summary>
        public static string FormatDuChampNombreDExpositionsIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampNombreDExpositionsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ RA incorrect.
        /// </summary>
        public static string FormatDuChampRAIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampRAIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Redshift incorrect.
        /// </summary>
        public static string FormatDuChampRedshiftIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampRedshiftIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Serveur pour Cartes du Ciel incorrect.
        /// </summary>
        public static string FormatDuChampServeurPourCartesDuCielIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampServeurPourCartesDuCielIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Température incorrect.
        /// </summary>
        public static string FormatDuChampTemperatureIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampTemperatureIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du champ Temps unitaire incorrect.
        /// </summary>
        public static string FormatDuChampTempsUnitaireIncorrect {
            get {
                return ResourceManager.GetString("FormatDuChampTempsUnitaireIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format du lieu incorrect.
        /// </summary>
        public static string FormatDuLieuIncorrect {
            get {
                return ResourceManager.GetString("FormatDuLieuIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format nombre d&apos;expositions incorrect.
        /// </summary>
        public static string FormatNombreDExpositionsIncorrect {
            get {
                return ResourceManager.GetString("FormatNombreDExpositionsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format temps d&apos;expositions incorrect.
        /// </summary>
        public static string FormatTempsDExpositionsIncorrect {
            get {
                return ResourceManager.GetString("FormatTempsDExpositionsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gain/ISO.
        /// </summary>
        public static string GainISO {
            get {
                return ResourceManager.GetString("GainISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grandeur max.
        /// </summary>
        public static string GrandeurMax {
            get {
                return ResourceManager.GetString("GrandeurMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grandeur min.
        /// </summary>
        public static string GrandeurMin {
            get {
                return ResourceManager.GetString("GrandeurMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IAU.
        /// </summary>
        public static string IAU {
            get {
                return ResourceManager.GetString("IAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il est impossible de modifier ou de supprimer un objet céleste du catalogue d&apos;origine..
        /// </summary>
        public static string IlEstImpossibleDeModifierOuDeSupprimerUnObjetCelesteDuCatalogueDOrigine {
            get {
                return ResourceManager.GetString("IlEstImpossibleDeModifierOuDeSupprimerUnObjetCelesteDuCatalogueDOrigine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur la recherche.
        /// </summary>
        public static string InformationsSurLaRecherche {
            get {
                return ResourceManager.GetString("InformationsSurLaRecherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur le DEC.
        /// </summary>
        public static string InformationsSurLeDEC {
            get {
                return ResourceManager.GetString("InformationsSurLeDEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur l&apos;enregistrement.
        /// </summary>
        public static string InformationsSurLEnregistrement {
            get {
                return ResourceManager.GetString("InformationsSurLEnregistrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur le RA.
        /// </summary>
        public static string InformationsSurLeRA {
            get {
                return ResourceManager.GetString("InformationsSurLeRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur les commentaires.
        /// </summary>
        public static string InformationsSurLesCommentaires {
            get {
                return ResourceManager.GetString("InformationsSurLesCommentaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur les dénominations.
        /// </summary>
        public static string InformationsSurLesDenominations {
            get {
                return ResourceManager.GetString("InformationsSurLesDenominations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur les dénominations des équipements.
        /// </summary>
        public static string InformationsSurLesDenominationsDesEquipements {
            get {
                return ResourceManager.GetString("InformationsSurLesDenominationsDesEquipements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur les dimensions.
        /// </summary>
        public static string InformationsSurLesDimensions {
            get {
                return ResourceManager.GetString("InformationsSurLesDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur les images des setups.
        /// </summary>
        public static string InformationsSurLesImagesDesSetups {
            get {
                return ResourceManager.GetString("InformationsSurLesImagesDesSetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur les images des sites d&apos;observations.
        /// </summary>
        public static string InformationsSurLesImagesDesSitesDObservations {
            get {
                return ResourceManager.GetString("InformationsSurLesImagesDesSitesDObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur les images et EXIF.
        /// </summary>
        public static string InformationsSurLesImagesEtEXIF {
            get {
                return ResourceManager.GetString("InformationsSurLesImagesEtEXIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur les images personnalisées.
        /// </summary>
        public static string InformationsSurLesImagesPersonnalisees {
            get {
                return ResourceManager.GetString("InformationsSurLesImagesPersonnalisees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur les setup.
        /// </summary>
        public static string InformationsSurLesSetup {
            get {
                return ResourceManager.GetString("InformationsSurLesSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations sur le tri de la liste des objets célestes.
        /// </summary>
        public static string InformationsSurLeTriDeLaListeDesObjetsCelestes {
            get {
                return ResourceManager.GetString("InformationsSurLeTriDeLaListeDesObjetsCelestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation de l&apos;application....
        /// </summary>
        public static string InitialisationDeLApplication {
            get {
                return ResourceManager.GetString("InitialisationDeLApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Janvier.
        /// </summary>
        public static string Janvier {
            get {
                return ResourceManager.GetString("Janvier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Juillet.
        /// </summary>
        public static string Juillet {
            get {
                return ResourceManager.GetString("Juillet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Juin.
        /// </summary>
        public static string Juin {
            get {
                return ResourceManager.GetString("Juin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La recherche trouve un trop grand nombre de résultat.
        /// </summary>
        public static string LaRechercheTrouveUnTropGrandNombreDeResultat {
            get {
                return ResourceManager.GetString("LaRechercheTrouveUnTropGrandNombreDeResultat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur du port doit correspondre à celle positionnée dans Stellarium, par défaut &apos;8090&apos;..
        /// </summary>
        public static string LaValeurDuPortDoitCorrespondreACellePositionneeDansStellariumParDefaut8090 {
            get {
                return ResourceManager.GetString("LaValeurDuPortDoitCorrespondreACellePositionneeDansStellariumParDefaut8090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les équipements avec un fond gris font partie d&apos;un setup et ne sont pas modifiables..
        /// </summary>
        public static string LesEquipementsAvecUnFondGrisFontPartieDUnSetupEtNeSontPasModifiables {
            get {
                return ResourceManager.GetString("LesEquipementsAvecUnFondGrisFontPartieDUnSetupEtNeSontPasModifiables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les observations associées à cette session seront également supprimées..
        /// </summary>
        public static string LesObservationsAssocieesACetteSessionSerontEgalementSupprimees {
            get {
                return ResourceManager.GetString("LesObservationsAssocieesACetteSessionSerontEgalementSupprimees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les sessions et observations associées à cet objet céleste seront également supprimées..
        /// </summary>
        public static string LesSessionsEtObservationsAssocieesACetObjetCelesteSerontEgalementSupprimees {
            get {
                return ResourceManager.GetString("LesSessionsEtObservationsAssocieesACetObjetCelesteSerontEgalementSupprimees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les [] signifient que le nom par défaut (nom de l&apos;équipement) est utilisé..
        /// </summary>
        public static string LesSignifientQueLeNomParDefautNomDeLEquipementEstUtilise {
            get {
                return ResourceManager.GetString("LesSignifientQueLeNomParDefautNomDeLEquipementEstUtilise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lieu.
        /// </summary>
        public static string Lieu {
            get {
                return ResourceManager.GetString("Lieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciel.
        /// </summary>
        public static string Logiciel {
            get {
                return ResourceManager.GetString("Logiciel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciels.
        /// </summary>
        public static string Logiciels {
            get {
                return ResourceManager.GetString("Logiciels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lors de la création des EXIF, vous pourrez choisir d&apos;inclure ou non cette image..
        /// </summary>
        public static string LorsDeLaCreationDesEXIFVousPourrezChoisirDInclureOuNonCetteImage {
            get {
                return ResourceManager.GetString("LorsDeLaCreationDesEXIFVousPourrezChoisirDInclureOuNonCetteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lune.
        /// </summary>
        public static string Lune {
            get {
                return ResourceManager.GetString("Lune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magnitude.
        /// </summary>
        public static string Magnitude {
            get {
                return ResourceManager.GetString("Magnitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magnitude (BMag).
        /// </summary>
        public static string MagnitudeBMag {
            get {
                return ResourceManager.GetString("MagnitudeBMag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mai.
        /// </summary>
        public static string Mai {
            get {
                return ResourceManager.GetString("Mai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mars.
        /// </summary>
        public static string Mars {
            get {
                return ResourceManager.GetString("Mars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour des fichiers de configuration.
        /// </summary>
        public static string MiseAJourDesFichiersDeConfiguration {
            get {
                return ResourceManager.GetString("MiseAJourDesFichiersDeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier le nom de l&apos;équipement dans le setup.
        /// </summary>
        public static string ModifierLeNomDeLEquipementDansLeSetup {
            get {
                return ResourceManager.GetString("ModifierLeNomDeLEquipementDansLeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier le nom de l&apos;équipement pour la session.
        /// </summary>
        public static string ModifierLeNomDeLEquipementPourLaSession {
            get {
                return ResourceManager.GetString("ModifierLeNomDeLEquipementPourLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier l&apos;image par défaut de la session.
        /// </summary>
        public static string ModifierLImageParDefautDeLaSession {
            get {
                return ResourceManager.GetString("ModifierLImageParDefautDeLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier l&apos;observation.
        /// </summary>
        public static string ModifierLObservation {
            get {
                return ResourceManager.GetString("ModifierLObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb équipements.
        /// </summary>
        public static string NbEquipements {
            get {
                return ResourceManager.GetString("NbEquipements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb expositions.
        /// </summary>
        public static string NbExpositions {
            get {
                return ResourceManager.GetString("NbExpositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb logiciels.
        /// </summary>
        public static string NbLogiciels {
            get {
                return ResourceManager.GetString("NbLogiciels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nb observations.
        /// </summary>
        public static string NbObservations {
            get {
                return ResourceManager.GetString("NbObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de l&apos;équipement dans la session.
        /// </summary>
        public static string NomDeLEquipementDansLaSession {
            get {
                return ResourceManager.GetString("NomDeLEquipementDansLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de l&apos;équipement dans le setup.
        /// </summary>
        public static string NomDeLEquipementDansLeSetup {
            get {
                return ResourceManager.GetString("NomDeLEquipementDansLeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous vous recommandons de garder un historique de vos setup et de leurs évolutions, par exemple &apos;Setup principal 2022-2023&apos;..
        /// </summary>
        public static string NousVousRecommandonsDeGarderUnHistoriqueDeVosSetupEtDeLeursEvolutions {
            get {
                return ResourceManager.GetString("NousVousRecommandonsDeGarderUnHistoriqueDeVosSetupEtDeLeursEvolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau logiciel.
        /// </summary>
        public static string NouveauLogiciel {
            get {
                return ResourceManager.GetString("NouveauLogiciel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau setup.
        /// </summary>
        public static string NouveauSetup {
            get {
                return ResourceManager.GetString("NouveauSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau site d&apos;observations.
        /// </summary>
        public static string NouveauSiteDObservations {
            get {
                return ResourceManager.GetString("NouveauSiteDObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvel équipement.
        /// </summary>
        public static string NouvelEquipement {
            get {
                return ResourceManager.GetString("NouvelEquipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle session d&apos;observations.
        /// </summary>
        public static string NouvelleSessionDObservations {
            get {
                return ResourceManager.GetString("NouvelleSessionDObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle version disponible.
        /// </summary>
        public static string NouvelleVersionDisponible {
            get {
                return ResourceManager.GetString("NouvelleVersionDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvel objet céleste.
        /// </summary>
        public static string NouvelObjetCeleste {
            get {
                return ResourceManager.GetString("NouvelObjetCeleste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Novembre.
        /// </summary>
        public static string Novembre {
            get {
                return ResourceManager.GetString("Novembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à objet affiché.
        /// </summary>
        public static string ObjetAffiche {
            get {
                return ResourceManager.GetString("ObjetAffiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet céleste.
        /// </summary>
        public static string ObjetCeleste {
            get {
                return ResourceManager.GetString("ObjetCeleste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet céleste indéfini.
        /// </summary>
        public static string ObjetCelesteIndéfini {
            get {
                return ResourceManager.GetString("ObjetCelesteIndéfini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à objets affichés.
        /// </summary>
        public static string ObjetsAffiches {
            get {
                return ResourceManager.GetString("ObjetsAffiches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à objets répertoriés.
        /// </summary>
        public static string ObjetsRepertories {
            get {
                return ResourceManager.GetString("ObjetsRepertories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Octobre.
        /// </summary>
        public static string Octobre {
            get {
                return ResourceManager.GetString("Octobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres de Cartes Du Ciel.
        /// </summary>
        public static string ParametresDeCartesDuCiel {
            get {
                return ResourceManager.GetString("ParametresDeCartesDuCiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres du plugin de contrôle à distance de Stellarium.
        /// </summary>
        public static string ParametresDuPluginDeControleADistanceDeStellarium {
            get {
                return ResourceManager.GetString("ParametresDuPluginDeControleADistanceDeStellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Par défaut, l&apos;image utilisée est la première du répertoire des images de la session..
        /// </summary>
        public static string ParDefautLImageUtiliseeEstLaPremiereDuRepertoireDesImagesDeLaSession {
            get {
                return ResourceManager.GetString("ParDefautLImageUtiliseeEstLaPremiereDuRepertoireDesImagesDeLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Par exemple des informations sur la météo, le vent, ....
        /// </summary>
        public static string ParExempleDesInformationsSurLaMeteoLeVent {
            get {
                return ResourceManager.GetString("ParExempleDesInformationsSurLaMeteoLeVent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Par exemple des informations sur l&apos;évolution de la météo, le vent, ....
        /// </summary>
        public static string ParExempleDesInformationsSurLEvolutionDeLaMeteoLeVent {
            get {
                return ResourceManager.GetString("ParExempleDesInformationsSurLEvolutionDeLaMeteoLeVent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Par exemple : &apos;Guidage : SW Evoguide ED50&apos;.
        /// </summary>
        public static string ParExempleGuidageSWEvoguideED50 {
            get {
                return ResourceManager.GetString("ParExempleGuidageSWEvoguideED50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Positionnez ici les informations nécessaires à la connexion au plugin de commande à distance de Stellarium..
        /// </summary>
        public static string PositionnezIciLesInformationsNecessairesALaConnexionAuPluginDeCommandeADistanceDeStellarium {
            get {
                return ResourceManager.GetString("PositionnezIciLesInformationsNecessairesALaConnexionAuPluginDeCommandeADistanceDe" +
                        "Stellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour des raisons de performances, le tri est désactivé pour les listes contenant plus de 1000 objets célestes..
        /// </summary>
        public static string PourDesRaisonsDePerformancesLeTriEstDesactivePourLesListesContenantPlusDe1000ObjetsCelestes {
            get {
                return ResourceManager.GetString("PourDesRaisonsDePerformancesLeTriEstDesactivePourLesListesContenantPlusDe1000Obje" +
                        "tsCelestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour exécuter Cartes du Ciel directement sur cet ordinateur, laissez la valeur par défaut &apos;127.0.0.1&apos;..
        /// </summary>
        public static string PourExecuterCartesDuCielDirectementSurCetOrdinateurLaissezLaValeurParDefaut127001 {
            get {
                return ResourceManager.GetString("PourExecuterCartesDuCielDirectementSurCetOrdinateurLaissezLaValeurParDefaut127001" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour exécuter Stellarium directement sur cet ordinateur, laissez la valeur par défaut &apos;localhost&apos;..
        /// </summary>
        public static string PourExecuterStellariumDirectementSurCetOrdinateurLaissezLaValeurParDefautLocalhost {
            get {
                return ResourceManager.GetString("PourExecuterStellariumDirectementSurCetOrdinateurLaissezLaValeurParDefautLocalhos" +
                        "t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour remettre le nom par défaut, supprimer le texte et laisser la zone vide..
        /// </summary>
        public static string PourRemettreLeNomParDefautSupprimerLeTexteEtLaisserLaZoneVide {
            get {
                return ResourceManager.GetString("PourRemettreLeNomParDefautSupprimerLeTexteEtLaisserLaZoneVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour une utilisation de ces données, même à des fins non commerciale, la validation des auteurs et des ayants droits est requise (Jean-Luc Vivo, Xavier Schildknecht, Dr Wolfgang Steinicke)..
        /// </summary>
        public static string PourUneUtilisationDeCesDonneesMemeADesFinsNonCommerciale {
            get {
                return ResourceManager.GetString("PourUneUtilisationDeCesDonneesMemeADesFinsNonCommerciale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour vous connecter à Cartes du Ciel sur un serveur, spécifiez ici l&apos;adresse IP du serveur..
        /// </summary>
        public static string PourVousConnecterACartesDuCielSurUnServeurSpecifiezIciLAdresseIPDuServeur {
            get {
                return ResourceManager.GetString("PourVousConnecterACartesDuCielSurUnServeurSpecifiezIciLAdresseIPDuServeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Première utilisation de l&apos;application.
        /// </summary>
        public static string PremiereUtilisationDeLApplication {
            get {
                return ResourceManager.GetString("PremiereUtilisationDeLApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RA.
        /// </summary>
        public static string RA {
            get {
                return ResourceManager.GetString("RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Redshift.
        /// </summary>
        public static string Redshift {
            get {
                return ResourceManager.GetString("Redshift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Référence sur l&apos;objet céleste incorrecte.
        /// </summary>
        public static string ReferenceSurLObjetCelesteIncorrecte {
            get {
                return ResourceManager.GetString("ReferenceSurLObjetCelesteIncorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remettre l&apos;image par défaut de la session.
        /// </summary>
        public static string RemettreLImageParDefautDeLaSession {
            get {
                return ResourceManager.GetString("RemettreLImageParDefautDeLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retirer le logiciel sélectionné de la session.
        /// </summary>
        public static string RetirerLeLogicielSelectionneDeLaSession {
            get {
                return ResourceManager.GetString("RetirerLeLogicielSelectionneDeLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retirer l&apos;équipement sélectionné de la session.
        /// </summary>
        public static string RetirerLEquipementSelectionneDeLaSession {
            get {
                return ResourceManager.GetString("RetirerLEquipementSelectionneDeLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde de la base de données.
        /// </summary>
        public static string SauvegardeDeLaBaseDeDonnees {
            get {
                return ResourceManager.GetString("SauvegardeDeLaBaseDeDonnees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde de la base de données de l&apos;application.
        /// </summary>
        public static string SauvegardeDeLaBaseDeDonneesDeLApplication {
            get {
                return ResourceManager.GetString("SauvegardeDeLaBaseDeDonneesDeLApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seeing.
        /// </summary>
        public static string Seeing {
            get {
                return ResourceManager.GetString("Seeing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection des logiciels.
        /// </summary>
        public static string SelectionDesLogiciels {
            get {
                return ResourceManager.GetString("SelectionDesLogiciels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection d&apos;une image pour la session du.
        /// </summary>
        public static string SelectionDUneImagePourLaSessionDu {
            get {
                return ResourceManager.GetString("SelectionDUneImagePourLaSessionDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection d&apos;une image pour le setup.
        /// </summary>
        public static string SelectionDUneImagePourLeSetup {
            get {
                return ResourceManager.GetString("SelectionDUneImagePourLeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélection d&apos;une image pour le site.
        /// </summary>
        public static string SelectionDUneImagePourLeSite {
            get {
                return ResourceManager.GetString("SelectionDUneImagePourLeSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner le répertoire où se trouve les images de la session.
        /// </summary>
        public static string SelectionnerLeRepertoireOuSeTrouveLesImagesDeLaSession {
            get {
                return ResourceManager.GetString("SelectionnerLeRepertoireOuSeTrouveLesImagesDeLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un objet céleste.
        /// </summary>
        public static string SelectionnerUnObjetCeleste {
            get {
                return ResourceManager.GetString("SelectionnerUnObjetCeleste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Septembre.
        /// </summary>
        public static string Septembre {
            get {
                return ResourceManager.GetString("Septembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à session affichée.
        /// </summary>
        public static string SessionAffichee {
            get {
                return ResourceManager.GetString("SessionAffichee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à session répertoriée.
        /// </summary>
        public static string SessionRepertoriee {
            get {
                return ResourceManager.GetString("SessionRepertoriee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sessions affichées.
        /// </summary>
        public static string SessionsAffichees {
            get {
                return ResourceManager.GetString("SessionsAffichees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sessions répertoriées.
        /// </summary>
        public static string SessionsRepertoriees {
            get {
                return ResourceManager.GetString("SessionsRepertoriees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Setups.
        /// </summary>
        public static string Setups {
            get {
                return ResourceManager.GetString("Setups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sites.
        /// </summary>
        public static string Sites {
            get {
                return ResourceManager.GetString("Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression de l&apos;objet céleste.
        /// </summary>
        public static string SuppressionDeLObjetCeleste {
            get {
                return ResourceManager.GetString("SuppressionDeLObjetCeleste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;un équipement.
        /// </summary>
        public static string SuppressionDUnEquipement {
            get {
                return ResourceManager.GetString("SuppressionDUnEquipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;une session d&apos;observations.
        /// </summary>
        public static string SuppressionDUneSessionDObservations {
            get {
                return ResourceManager.GetString("SuppressionDUneSessionDObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;un logiciel.
        /// </summary>
        public static string SuppressionDUnLogiciel {
            get {
                return ResourceManager.GetString("SuppressionDUnLogiciel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;un objet céleste.
        /// </summary>
        public static string SuppressionDUnObjetCeleste {
            get {
                return ResourceManager.GetString("SuppressionDUnObjetCeleste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;un setup.
        /// </summary>
        public static string SuppressionDUnSetup {
            get {
                return ResourceManager.GetString("SuppressionDUnSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression d&apos;un site.
        /// </summary>
        public static string SuppressionDUnSite {
            get {
                return ResourceManager.GetString("SuppressionDUnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string Supprimer {
            get {
                return ResourceManager.GetString("Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer l&apos;image du setup.
        /// </summary>
        public static string SupprimerLImageDuSetup {
            get {
                return ResourceManager.GetString("SupprimerLImageDuSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer l&apos;image du site d&apos;observations.
        /// </summary>
        public static string SupprimerLImageDuSiteDObservations {
            get {
                return ResourceManager.GetString("SupprimerLImageDuSiteDObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer l&apos;observation de la session.
        /// </summary>
        public static string SupprimerLObservationDeLaSession {
            get {
                return ResourceManager.GetString("SupprimerLObservationDeLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sur.
        /// </summary>
        public static string Sur {
            get {
                return ResourceManager.GetString("Sur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sur l&apos;objet.
        /// </summary>
        public static string SurLObjet {
            get {
                return ResourceManager.GetString("SurLObjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Température.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps d&apos;exposition total.
        /// </summary>
        public static string TempsDExpositionTotal {
            get {
                return ResourceManager.GetString("TempsDExpositionTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps total.
        /// </summary>
        public static string TempsTotal {
            get {
                return ResourceManager.GetString("TempsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temps unitaire.
        /// </summary>
        public static string TempsUnitaire {
            get {
                return ResourceManager.GetString("TempsUnitaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous.
        /// </summary>
        public static string Tous {
            get {
                return ResourceManager.GetString("Tous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toute utilisation des données du catalogue à des fins commerciales est strictement prohibée..
        /// </summary>
        public static string TouteUtilisationDesDonneesDuCatalogueADesFinsCommercialesEstStrictementProhibee {
            get {
                return ResourceManager.GetString("TouteUtilisationDesDonneesDuCatalogueADesFinsCommercialesEstStrictementProhibee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tps total (brutes).
        /// </summary>
        public static string TpsTotalBrutes {
            get {
                return ResourceManager.GetString("TpsTotalBrutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type d&apos;objets célestes.
        /// </summary>
        public static string TypeDObjetsCelestes {
            get {
                return ResourceManager.GetString("TypeDObjetsCelestes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type Objet céleste.
        /// </summary>
        public static string TypeObjetCeleste {
            get {
                return ResourceManager.GetString("TypeObjetCeleste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vérification de la présence d&apos;une nouvelle version de l&apos;application.
        /// </summary>
        public static string VerificationDeLaPresenceDUneNouvelleVersionDeLApplication {
            get {
                return ResourceManager.GetString("VerificationDeLaPresenceDUneNouvelleVersionDeLApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez affiner votre recherche..
        /// </summary>
        public static string VeuillezAffinerVotreRecherche {
            get {
                return ResourceManager.GetString("VeuillezAffinerVotreRecherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez donner un nom pour l&apos;équipement dans la session.
        /// </summary>
        public static string VeuillezDonnerUnNomPourLEquipementDansLaSession {
            get {
                return ResourceManager.GetString("VeuillezDonnerUnNomPourLEquipementDansLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez donner un nom pour l&apos;équipement dans le setup.
        /// </summary>
        public static string VeuillezDonnerUnNomPourLEquipementDansLeSetup {
            get {
                return ResourceManager.GetString("VeuillezDonnerUnNomPourLEquipementDansLeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir au moins 3 caractères afin de lancer la recherche..
        /// </summary>
        public static string VeuillezSaisirAuMoins3CaracteresAfinDeLancerLaRecherche {
            get {
                return ResourceManager.GetString("VeuillezSaisirAuMoins3CaracteresAfinDeLancerLaRecherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner le répertoire contenant les images de la session d&apos;observations.
        /// </summary>
        public static string VeuillezSelectionnerLeRepertoireContenantLesImagesDeLaSessionDObservations {
            get {
                return ResourceManager.GetString("VeuillezSelectionnerLeRepertoireContenantLesImagesDeLaSessionDObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez séparer les dénominations par des &apos;;&apos;.
        /// </summary>
        public static string VeuillezSeparerLesDenominationsParDes {
            get {
                return ResourceManager.GetString("VeuillezSeparerLesDenominationsParDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visualisation EXIF de la session.
        /// </summary>
        public static string VisualisationEXIFDeLaSession {
            get {
                return ResourceManager.GetString("VisualisationEXIFDeLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous supprimer la session du.
        /// </summary>
        public static string VoulezVousSupprimerLaSessionDu {
            get {
                return ResourceManager.GetString("VoulezVousSupprimerLaSessionDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous supprimer le logiciel.
        /// </summary>
        public static string VoulezVousSupprimerLeLogiciel {
            get {
                return ResourceManager.GetString("VoulezVousSupprimerLeLogiciel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous supprimer l&apos;équipement.
        /// </summary>
        public static string VoulezVousSupprimerLEquipement {
            get {
                return ResourceManager.GetString("VoulezVousSupprimerLEquipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous supprimer le setup.
        /// </summary>
        public static string VoulezVousSupprimerLeSetup {
            get {
                return ResourceManager.GetString("VoulezVousSupprimerLeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous supprimer le site.
        /// </summary>
        public static string VoulezVousSupprimerLeSite {
            get {
                return ResourceManager.GetString("VoulezVousSupprimerLeSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous supprimer l&apos;objet céleste.
        /// </summary>
        public static string VoulezVousSupprimerLObjetCeleste {
            get {
                return ResourceManager.GetString("VoulezVousSupprimerLObjetCeleste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez définir le répertoire des images de la session pour afficher les fonctionnalités &apos;images&apos;, &apos;EXIF&apos; et &apos;image personnalisée&apos;..
        /// </summary>
        public static string VousDevezDefinirLeRepertoireDesImagesDeLaSessionPourAfficherLesFonctionnalites {
            get {
                return ResourceManager.GetString("VousDevezDefinirLeRepertoireDesImagesDeLaSessionPourAfficherLesFonctionnalites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez ajouter un commentaire à votre session d&apos;observations..
        /// </summary>
        public static string VousPouvezAjouterUnCommentaireAVotreSessionDObservations {
            get {
                return ResourceManager.GetString("VousPouvezAjouterUnCommentaireAVotreSessionDObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez ajouter un commentaire spécifique à votre observation..
        /// </summary>
        public static string VousPouvezAjouterUnCommentaireSpecifiqueAVotreObservation {
            get {
                return ResourceManager.GetString("VousPouvezAjouterUnCommentaireSpecifiqueAVotreObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez ajouter une image à votre setup..
        /// </summary>
        public static string VousPouvezAjouterUneImageAVotreSetup {
            get {
                return ResourceManager.GetString("VousPouvezAjouterUneImageAVotreSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez ajouter une image à votre site d&apos;observation..
        /// </summary>
        public static string VousPouvezAjouterUneImageAVotreSiteDObservation {
            get {
                return ResourceManager.GetString("VousPouvezAjouterUneImageAVotreSiteDObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez ici ajouter ou supprimer des équipements à votre setup (exemple : télescope, monture, caméra)..
        /// </summary>
        public static string VousPouvezIciAjouterOuSupprimerDesEquipementsAVotreSetup {
            get {
                return ResourceManager.GetString("VousPouvezIciAjouterOuSupprimerDesEquipementsAVotreSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez spécifier une image personnalisée pour la session..
        /// </summary>
        public static string VousPouvezSpecifierUneImagePersonnaliseePourLaSession {
            get {
                return ResourceManager.GetString("VousPouvezSpecifierUneImagePersonnaliseePourLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez spécifier un nom différent pour l&apos;équipement tel qu&apos;il apparaîtra dans la session..
        /// </summary>
        public static string VousPouvezSpecifierUnNomDifferentPourLEquipementTelQuIlApparaitraDansLaSession {
            get {
                return ResourceManager.GetString("VousPouvezSpecifierUnNomDifferentPourLEquipementTelQuIlApparaitraDansLaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez spécifier un nom différent pour l&apos;équipement tel qu&apos;il apparaîtra dans le setup..
        /// </summary>
        public static string VousPouvezSpecifierUnNomDifferentPourLEquipementTelQuIlApparaitraDansLeSetup {
            get {
                return ResourceManager.GetString("VousPouvezSpecifierUnNomDifferentPourLEquipementTelQuIlApparaitraDansLeSetup", resourceCulture);
            }
        }
    }
}
